import { RegularExpressionConfig } from '@core/configs';

export abstract class DeclarationPropertyValueAllowedListConfig {
	public static readonly VALUES = {
		color: [
			'/^rgba/',
			'inherit',
			'initial',
			'none',
			'transparent',
			'currentColor',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
		'border-color': [
			'/^rgba/',
			'inherit',
			'initial',
			'none',
			'transparent',
			'currentColor',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
		'outline-color': [
			'/^rgba/',
			'inherit',
			'initial',
			'none',
			'transparent',
			'currentColor',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
		'background-color': [
			'/^rgba/',
			'inherit',
			'initial',
			'none',
			'transparent',
			'currentColor',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
		'font-family': [
			'/^url/',
			'inherit',
			'initial',
			'none',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
		'font-size': [
			'inherit',
			'initial',
			'none',
			'0',
			'1',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
		size: [
			'inherit',
			'initial',
			'none',
			'0',
			'1',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
		'line-height': [
			'inherit',
			'initial',
			'none',
			'0',
			'1',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
		stroke: [
			'/^rgba/',
			'inherit',
			'initial',
			'none',
			'transparent',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
		fill: [
			'/^rgba/',
			'inherit',
			'initial',
			'none',
			'transparent',
			'currentColor',
			RegularExpressionConfig.SCSS_VARIABLE,
			RegularExpressionConfig.CSS_VARIABLE,
			RegularExpressionConfig.SCSS_SCOPE_VARIABLE,
		],
	};
}
