import { OrderContentHelper } from '../../helpers';

export const ORDER_CONTENT_PSEUDO_ELEMENTS = OrderContentHelper.createPseudoElements([
	'first-letter',
	'before',
	'after',
	'placeholder',
	'first-line',
	'selection',
	'backdrop',
	'marker',
	'spelling-error',
	'grammar-error',
	'cue',
	'file-selector-button',
	'highlight',
	'slotted',
	'target-text',
	'-webkit-input-placeholder',
	'-moz-placeholder',
	'-ms-input-placeholder',
	'-ms-clear',
	'-ms-reveal',
	'-webkit-search-cancel-button',
	'-webkit-search-decoration',
	'-webkit-search-results-button',
	'-webkit-search-results-decoration',
	'-webkit-slider-runnable-track',
	'-webkit-slider-thumb',
	'-webkit-media-controls-panel',
	'-webkit-media-controls-play-button',
	'-webkit-media-controls-volume-slider',
	'[a-z]',
]);
