import { RULE_PROPERTY_UNIT_ALLOWED_LIST } from './rule-property-unit-allowed-list.config';

describe('RULE_PROPERTY_UNIT_ALLOWED_LIST', () => {
	it('should have the following value', () => {
		expect(RULE_PROPERTY_UNIT_ALLOWED_LIST).toEqual({
			width: ['px', '%', 'vw'],
			'min-width': ['px', '%', 'vw'],
			'max-width': ['px', '%', 'vw'],
			height: ['px', '%', 'vh'],
			'min-height': ['px', '%', 'vh'],
			'max-height': ['px', '%', 'vh'],
			'/^padding/': ['px', '%'],
			'/^margin/': ['px', '%'],
			top: ['px', '%'],
			right: ['px', '%'],
			bottom: ['px', '%'],
			left: ['px', '%'],
			'grid-auto-columns': ['px', '%', 'fr'],
			'grid-auto-rows': ['px', '%', 'fr'],
			'grid-template-columns': ['px', '%', 'fr'],
			'grid-template-rows': ['px', '%', 'fr'],
			gap: ['px', '%'],
			'grid-gap': ['px', '%'],
			'grid-column-gap': ['px', '%'],
			'grid-row-gap': ['px', '%'],
			'column-gap': ['px', '%'],
			'flex-basis': ['px', '%'],
			border: ['px'],
			'border-width': ['px'],
			'/^border-(top|right|bottom|left)/': ['px'],
			'/^border-(top|right|bottom|left)-width/': ['px'],
			'outline-width': ['px'],
			'box-shadow': ['px', '%'],
			'text-shadow': ['px', '%'],
			'background-position': ['px', '%'],
			'background-size': ['px', '%'],
			'object-position': ['px', '%'],
			'border-radius': ['px', '%'],
			'/^border-(top|bottom)-(left|right)-radius/': ['px', '%'],
			'font-size': [],
			'line-height': [],
			animation: ['ms'],
			'animation-duration': ['ms'],
			'transition-duration': ['ms'],
			transition: ['ms'],
		});
	});
});
